## Day 2 Lecture

In [7]:
#Think of packages as the "DLC" of Python. We need 2, and are making aliases of pd
import pandas as pd

In [8]:
#We are using pandas to get the data into our computer.
pd.read_csv('sample_data/california_housing_train.csv')
#Note the '' or "" around the text, this means "read the whole thing as one string."
#    In real life, when I make air quotes I mean "take this literally - but not with its normal meaning", and I find similarities here.
#Note also that the "/" direction matters - "\" is sometimes an "escape character"  Consider trying "\\" instead in some cases.

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [9]:
#If we don't save it as an object, it will just read it, print to the screen, and then disappear without saving it. :0!
myDataObj = pd.read_csv('sample_data/california_housing_train.csv')

In [10]:
#Now we can access the "object", this one is called a dataframe, often abbreviated df
myDataObj.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [11]:
#I like this name better so I will use it.
df_house = myDataObj

### From before, we can select columns in many ways:

In [12]:
df_house.iloc[:,2]

0        15.0
1        19.0
2        17.0
3        14.0
4        20.0
         ...
16995    52.0
16996    36.0
16997    17.0
16998    19.0
16999    52.0
Name: housing_median_age, Length: 17000, dtype: float64

In [13]:
df_house["housing_median_age"]

0        15.0
1        19.0
2        17.0
3        14.0
4        20.0
         ...
16995    52.0
16996    36.0
16997    17.0
16998    19.0
16999    52.0
Name: housing_median_age, Length: 17000, dtype: float64

#### And cells can be selected individually

In [14]:
df_house.iloc[2,0]

np.float64(-114.56)

In [15]:
#Note this selects a list. Then after the list is picked, we take the 0th element from it.
df_house["housing_median_age"][0]

np.float64(15.0)

### Note sometimes you want your output as a data frame, this is not a list or vector, this is a data frame object much like the collection above.

In [16]:
df_house[["housing_median_age"]]  #see the output is different? Py recognizes this difference.

       housing_median_age
0                    15.0
1                    19.0
2                    17.0
3                    14.0
4                    20.0
...                   ...
16995                52.0
16996                36.0
16997                17.0
16998                19.0
16999                52.0

[17000 rows x 1 columns]

# Utilizing the power of dataframes to get summary statistics

In [17]:
#Np float means data out is a "float" as opposed to an "int" or a "string". Means it is a decimal with up to 64 entries.
df_house["housing_median_age"].mean()

np.float64(28.58935294117647)

In [18]:
df_house["housing_median_age"].median()

29.0

In [19]:
#Note this outputs a LIST!  unexpected. Output is 52, list has ONE element in it. A waste of a list.
df_house["housing_median_age"].mode()

0    52.0
Name: housing_median_age, dtype: float64

In [20]:
df_house["housing_median_age"].mode()[0] #This selects the 0th element of the list.

np.float64(52.0)

In [21]:
#Next line doesn't work, will error!
#df_house["housing_median_age"].range()

### Getting Range, Storing a value

In [22]:
theMedianHouseAge = df_house["housing_median_age"].median()

In [23]:
#Value is now kept in memory under this name.
theMedianHouseAge

29.0

In [24]:
#Object is manipulable.
theMedianHouseAge = theMedianHouseAge + 6

In [25]:
theMedianHouseAge

35.0

In [26]:
df_house["housing_median_age"].min()

1.0

In [27]:
df_house["housing_median_age"].max()

52.0

In [28]:
#range is:

In [29]:
52-1

51

In [30]:
df_house["housing_median_age"].max() - df_house["housing_median_age"].min() #this is how to calculate range. Easily extensible!

51.0

# Functionalizing Code

In [31]:
#define function, names BSWrange, reqires input "dataFrameIn"
def BSWrange(dataFrameIn):
    #Indent 4
    return dataFrameIn["housing_median_age"].max() - dataFrameIn["housing_median_age"].min()

In [32]:
BSWrange(df_house)

51.0

Code can be ran on any data set that has "housing_median_age"

In [33]:
def BSWrangeAlt(dataColIn):
    #Indent 4
    return dataColIn.max() - dataColIn.min()

In [34]:
BSWrangeAlt(df_house["housing_median_age"])

51.0

Note function changed. Try changing inputs between BSWrange and BSWrangeAlt and see what happens.

## Activity:
Try to make a function that executes "mean".
Hint below (and above)!  Note we don't need to use range here. See the output is the actual values of the column.

In [ ]:
j = 0
for i in df_house["housing_median_age"]:
    j = 1
    print(i, j)