## Day 1 Lecture

Let's explore data storage in Python!

Sections are **Markdown** cells, and they can make cool formatting things: https://www.markdownguide.org/basic-syntax/

In [ ]:
#Think of packages as the "DLC" of Python. We need 2, and are making aliases of pd and plt
import pandas as pd

In [ ]:
#We are using pandas to get the data into our computer.
titanicData = pd.read_csv('G:/My Drive/Course Info/Classes/BDA_301_2025_Spring/Data/titanic3.csv')
#Note the '' or "" around the text, this means "read the whole thing as one string."
#    In real life, when I make air quotes I mean "take this literally - but not with its normal meaning", and I find similarities here.
#Note also that the "/" direction matters - "\" is sometimes an "escape character"  Consider trying "\\" instead in some cases.

In [ ]:
#If we don't save it as an object, it will just read it, print to the screen, and then disappear without saving it. :0!
pd.read_csv('G:/My Drive/Course Info/Classes/BDA_301_2025_Spring/Data/titanic3.csv')

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1305,3.0,0.0,"Zabour, Miss. Thamine",female,NaN,1.0,0.0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3.0,0.0,"Zakarian, Mr. Mapriededer",male,26.5000,0.0,0.0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3.0,0.0,"Zakarian, Mr. Ortin",male,27.0000,0.0,0.0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3.0,0.0,"Zimmerman, Mr. Leo",male,29.0000,0.0,0.0,315082,7.8750,NaN,S,NaN,NaN,NaN
1309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Now we can access the "object", this one is called a dataframe, often abbreviated df
titanicData['name']

0                         Allen, Miss. Elisabeth Walton
1                        Allison, Master. Hudson Trevor
2                          Allison, Miss. Helen Loraine
3                  Allison, Mr. Hudson Joshua Creighton
4       Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
                             ...
1305                              Zabour, Miss. Thamine
1306                          Zakarian, Mr. Mapriededer
1307                                Zakarian, Mr. Ortin
1308                                 Zimmerman, Mr. Leo
1309                                                NaN
Name: name, Length: 1310, dtype: object

In [ ]:
print(titanicData['age'].mean())

29.8811345124283

In [ ]:
titanicData.head  #Notice the difference

<bound method NDFrame.head of       pclass  survived                                             name  \
0        1.0       1.0                    Allen, Miss. Elisabeth Walton
1        1.0       1.0                   Allison, Master. Hudson Trevor
2        1.0       0.0                     Allison, Miss. Helen Loraine
3        1.0       0.0             Allison, Mr. Hudson Joshua Creighton
4        1.0       0.0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
...      ...       ...                                              ...
1305     3.0       0.0                            Zabour, Miss. Thamine
1306     3.0       0.0                        Zakarian, Mr. Mapriededer
1307     3.0       0.0                              Zakarian, Mr. Ortin
1308     3.0       0.0                               Zimmerman, Mr. Leo
1309     NaN       NaN                                              NaN

         sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.0000    0.0    0.0   24160  211.3375       B5        S    2
1       male   0.9167    1.0    2.0  113781  151.5500  C22 C26        S   11
2     female   2.0000    1.0    2.0  113781  151.5500  C22 C26        S  NaN
3       male  30.0000    1.0    2.0  113781  151.5500  C22 C26        S  NaN
4     female  25.0000    1.0    2.0  113781  151.5500  C22 C26        S  NaN
...      ...      ...    ...    ...     ...       ...      ...      ...  ...
1305  female      NaN    1.0    0.0    2665   14.4542      NaN        C  NaN
1306    male  26.5000    0.0    0.0    2656    7.2250      NaN        C  NaN
1307    male  27.0000    0.0    0.0    2670    7.2250      NaN        C  NaN
1308    male  29.0000    0.0    0.0  315082    7.8750      NaN        S  NaN
1309     NaN      NaN    NaN    NaN     NaN       NaN      NaN      NaN  NaN

       body                        home.dest
0       NaN                     St Louis, MO
1       NaN  Montreal, PQ / Chesterville, ON
2       NaN  Montreal, PQ / Chesterville, ON
3     135.0  Montreal, PQ / Chesterville, ON
4       NaN  Montreal, PQ / Chesterville, ON
...     ...                              ...
1305    NaN                              NaN
1306  304.0                              NaN
1307    NaN                              NaN
1308    NaN                              NaN
1309    NaN                              NaN

[1310 rows x 14 columns]>

# Accessing Rows and Columns

In [ ]:
titanicData['age'] #Returns a vector

0       29.0000
1        0.9167
2        2.0000
3       30.0000
4       25.0000
         ...
1305        NaN
1306    26.5000
1307    27.0000
1308    29.0000
1309        NaN
Name: age, Length: 1310, dtype: float64

In [ ]:
titanicData[['sex', 'name', 'fare']] #Returns a df

         sex                                             name      fare
0     female                    Allen, Miss. Elisabeth Walton  211.3375
1       male                   Allison, Master. Hudson Trevor  151.5500
2     female                     Allison, Miss. Helen Loraine  151.5500
3       male             Allison, Mr. Hudson Joshua Creighton  151.5500
4     female  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  151.5500
...      ...                                              ...       ...
1305  female                            Zabour, Miss. Thamine   14.4542
1306    male                        Zakarian, Mr. Mapriededer    7.2250
1307    male                              Zakarian, Mr. Ortin    7.2250
1308    male                               Zimmerman, Mr. Leo    7.8750
1309     NaN                                              NaN       NaN

[1310 rows x 3 columns]

In [ ]:
titanicData.iloc[0]  # First row

pclass                                 1.0
survived                               1.0
name         Allen, Miss. Elisabeth Walton
sex                                 female
age                                   29.0
sibsp                                  0.0
parch                                  0.0
ticket                               24160
fare                              211.3375
cabin                                   B5
embarked                                 S
boat                                     2
body                                   NaN
home.dest                     St Louis, MO
Name: 0, dtype: object

In [ ]:
titanicData.iloc[1:5]  # Rows from index 1 to 4 (excludes index 5)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.55,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.55,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.55,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.55,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [ ]:
titanicData.loc[1]  # Select by row label

pclass                                   1.0
survived                                 1.0
name          Allison, Master. Hudson Trevor
sex                                     male
age                                   0.9167
sibsp                                    1.0
parch                                    2.0
ticket                                113781
fare                                  151.55
cabin                                C22 C26
embarked                                   S
boat                                      11
body                                     NaN
home.dest    Montreal, PQ / Chesterville, ON
Name: 1, dtype: object

In [ ]:
titanicData.loc[1:5, ['home.dest', 'ticket']]  # Select rows and specific columns

                         home.dest  ticket
1  Montreal, PQ / Chesterville, ON  113781
2  Montreal, PQ / Chesterville, ON  113781
3  Montreal, PQ / Chesterville, ON  113781
4  Montreal, PQ / Chesterville, ON  113781
5                     New York, NY   19952

In [ ]:
titanicData[titanicData['age'] > 50]  # Rows where the value in 'column_name' is greater than 50

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
6,1.0,1.0,"Andrews, Miss. Kornelia Theodosia",female,63.0,1.0,0.0,13502,77.9583,D7,S,10,NaN,"Hudson, NY"
8,1.0,1.0,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2.0,0.0,11769,51.4792,C101,S,D,NaN,"Bayside, Queens, NY"
9,1.0,0.0,"Artagaveytia, Mr. Ramon",male,71.0,0.0,0.0,PC 17609,49.5042,NaN,C,NaN,22.0,"Montevideo, Uruguay"
14,1.0,1.0,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0.0,0.0,27042,30.0000,A23,S,B,NaN,"Hessle, Yorks"
33,1.0,1.0,"Bonnell, Miss. Elizabeth",female,58.0,0.0,0.0,113783,26.5500,C103,S,8,NaN,"Birkdale, England Cleveland, Ohio"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1068,3.0,0.0,"Nysveen, Mr. Johan Hansen",male,61.0,0.0,0.0,345364,6.2375,NaN,S,NaN,NaN,NaN
1225,3.0,0.0,"Storey, Mr. Thomas",male,60.5,0.0,0.0,3701,NaN,NaN,S,NaN,261.0,NaN
1235,3.0,0.0,"Svensson, Mr. Johan",male,74.0,0.0,0.0,347060,7.7750,NaN,S,NaN,NaN,NaN
1261,3.0,1.0,"Turkula, Mrs. (Hedwig)",female,63.0,0.0,0.0,4134,9.5875,NaN,S,15,NaN,NaN
1287,3.0,0.0,"Widegren, Mr. Carl/Charles Peter",male,51.0,0.0,0.0,347064,7.7500,NaN,S,NaN,NaN,NaN

In [ ]:
titanicData[(titanicData['age'] > 30) & (titanicData['pclass'] == 1)]

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
5,1.0,1.0,"Anderson, Mr. Harry",male,48.0,0.0,0.0,19952,26.5500,E12,S,3,NaN,"New York, NY"
6,1.0,1.0,"Andrews, Miss. Kornelia Theodosia",female,63.0,1.0,0.0,13502,77.9583,D7,S,10,NaN,"Hudson, NY"
7,1.0,0.0,"Andrews, Mr. Thomas Jr",male,39.0,0.0,0.0,112050,0.0000,A36,S,NaN,NaN,"Belfast, NI"
8,1.0,1.0,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2.0,0.0,11769,51.4792,C101,S,D,NaN,"Bayside, Queens, NY"
9,1.0,0.0,"Artagaveytia, Mr. Ramon",male,71.0,0.0,0.0,PC 17609,49.5042,NaN,C,NaN,22.0,"Montevideo, Uruguay"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,1.0,1.0,"Widener, Mrs. George Dunton (Eleanor Elkins)",female,50.0,1.0,1.0,113503,211.5000,C80,C,4,NaN,"Elkins Park, PA"
316,1.0,0.0,"Williams, Mr. Charles Duane",male,51.0,0.0,1.0,PC 17597,61.3792,NaN,C,NaN,NaN,"Geneva, Switzerland / Radnor, PA"
319,1.0,1.0,"Wilson, Miss. Helen Alice",female,31.0,0.0,0.0,16966,134.5000,E39 E41,C,3,NaN,NaN
321,1.0,0.0,"Wright, Mr. George",male,62.0,0.0,0.0,113807,26.5500,NaN,S,NaN,NaN,"Halifax, NS"
322,1.0,1.0,"Young, Miss. Marie Grice",female,36.0,0.0,0.0,PC 17760,135.6333,C32,C,8,NaN,"New York, NY / Washington, DC"

In [ ]:
titanicData["sex"][1]

'male'

# Data Types

int64: Integer values (whole numbers).

float64: Decimal values.

object: Typically used for text or string values.

datetime64: Dates and times.

bool: Boolean values (True/False).

In [ ]:
#Important fix, sometimes columns that should be numbers accidentally are read as strings.  No example in actual data right now.
# titanicData['age'] = titanicData['age'].astype('int64')  # Convert to integer

# Advanced actions: Groupby, Order of operations.

In [ ]:
# Let's test the first part.
# What do you think .groupby('sex') does?
# How about .size()?

collapsedTitanic = titanicData.groupby('sex').size()
collapsedTitanic

#You will eventually need this groupby function, it is in about 40% of projects.

sex
female    466
male      843
dtype: int64

In [ ]:
#What can I tell from this? Which class would I rather be from?
titanicData.groupby(['survived','sex']).size()

survived  sex
0.0       female    127
          male      682
1.0       female    339
          male      161
dtype: int64

In [ ]:
#Why is this better - and what did I do?
titanicData.groupby(['survived','sex']).size()/titanicData.groupby(['sex']).size() * 100
#Always manually check your plan works.

survived  sex
0.0       female    27.253219
          male      80.901542
1.0       female    72.746781
          male      19.098458
dtype: float64

That looks good.
Good code often gives the vibe of polished perfection - it should never error or warn when it runs.

The purpose of showing this error is to make you feel better and understand this is **completely normal**.

I would now:
1. Go back and clean up my incorrect/bad code.
2. RERUN everything from the first cell. (Restart Runtime CTRL+M, Run All CTRL+F9)

You will end up with bad code if you only do one cleanup at the end. Why? If you're too tired to do it immediately, you'll be too tired to do it at the end.

## Problem Solving

1) Do your own groupbys on the titanic data now, and make a new chart of this data (one I haven't shown you).
2) Without looking at the contents, load the dataset battleship.csv. We will play battleship now together.  I get 3 guesses for each of yours.
3) Optional, using the commands we have now, make a script that searches the field for battleships automatically on a df and shouts HIT whenever a ship is hit.